Repository xmos/xscope_fileio, pull requests merged in 2022-07, with the labels that each got.

#39 Increase delay in xscope_fread() from 0.1 ms to 0.5 ms
  CHANGELOG.rst
  xscope_fileio/module_build_info
  xscope_fileio/src/xscope_io_device.c
Labels: bug

#41 Bugfix/xscope host not connected
  CHANGELOG.rst
  README.rst
  xscope_fileio/api/xscope_io_device.h
  xscope_fileio/src/xscope_io_device.c
Labels: type:bug, size:S

#42 Corrected change log
  CHANGELOG.rst
Labels: type:documentation, size:S

#40 Prepare release v1.1.1
  CHANGELOG.rst
  README.rst
  xscope_fileio/api/xscope_io_device.h
  xscope_fileio/module_build_info
  xscope_fileio/src/xscope_io_device.c
Labels: size:S
